# Base configs
baseurl: "https://averagenl.github.io"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Daan"
subtitle: "See the world through my eyes!"
author: "Daan van Monsjou"
header:
 title: "Photography"
 subtitle: "by Daan"
footer:
 name: "Hey there, my name is Daan"
 bio: "I am a street photographer from the Netherlands. I try to capture beautiful moments, whatever they may be.."
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/daantakespics"
